### ISSUE TITLE
Colors fade after the first Signature is written

### ISSUE THREAD

**Issue by natgeo-wong** [jkrumbiegel/ClearStacktrace.jl#3]
Hi!  I love this package.  Just one thing that I found

The colors fade after the first error with a signature, as seen below on two different formats for te macOS shell

```
julia> versioninfo()
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
````

![Screen Shot 2020-05-25 at 13 52 25](https://user-images.githubusercontent.com/36907442/82834578-9412e680-9e8f-11ea-8d80-c53b4168d8d8.png)
![Screen Shot 2020-05-25 at 13 50 49](https://user-images.githubusercontent.com/36907442/82834579-9412e680-9e8f-11ea-8888-95259ff5fae8.png)

**Comment by jkrumbiegel** [comment]
That is weird, I haven't seen this behavior before. I think this happens because the default colors for the signature are in the 16 million color mode, while all the others use the default palette. So it seems that using these special colors in your REPL messes up all following text, while still keeping the general shade of the default colors intact. Either I'm using Crayons wrong, or your version of Crayons is outdated, or that's a bug in Crayons.

**Comment by jkrumbiegel** [comment]
ah, additionally it seems that the signature colors are not printed correctly in your REPL, so it seems not to support that color mode. they should be slightly red, blue, green tinted shades of gray like this 
<img width="462" alt="grafik" src="https://user-images.githubusercontent.com/22495855/82869089-fcb0a080-9f2d-11ea-820d-5968a97be18b.png">

**Comment by jkrumbiegel** [comment]
you could replace the colors in the `TYPECOLORS` constant to some other supported colors, it's defined here https://github.com/jkrumbiegel/ClearStacktrace.jl/blob/master/src/ClearStacktrace.jl#L15

**Comment by natgeo-wong** [comment]
The grayscale fix works!!!  Thanks so much!
